In [1]:
import pandas as pd
import numpy as np

In [2]:
# (2*(x-3)**2 + 4)
# (cos(2*x))


def f(x):
    return f"{(3*x + 4):.2f}"

def fdash(x):
    return 4*(x-3)

In [3]:
def convert(arr):
    arr = arr.T
    for j in range(len(arr)):
        x = arr[j]
        temp = []
        for i in x:
            temp.append(fdash(i))
        xdash = np.array(temp)
        temp = []
        for i in xdash:
            temp.append(f(i))
        arr[j] = np.array(temp)
    print(arr)
    arr = arr.T
    return arr

In [4]:
sa=2
sb=3
sc=4

sxy = np.array(
    [[1.0,sa,0,0],
    [sb,sa*sb+1,0,0],
    [sc,sa*sc+1,1,0],      
    [0,0,0,1]]
)

syz = np.array(
    [[1.0,sa,sa+sa*sb,0],
    [0,1,sb,0],
    [0,sc,sa*sc+1,0],      
    [0,0,0,1]]
) 

szx = np.array(
    [[1+sa*sc,0,sa,0.0],
    [sb+sb*sc,1,sb,0],
    [sc,0,1,0],
    [0,0,0,1]]
)


In [5]:
def sharing(trip):
  #print(trip)
  tp_arr = trip.transpose()
  #print(tp_arr)
  one = np.ones(tp_arr[0].shape)
  #print(one)
  tp_arr = np.concatenate((tp_arr,[one]))
  print(tp_arr)

  a = np.array(np.matrix(sxy)*np.matrix(tp_arr))
  a = np.array(np.matrix(syz)*np.matrix(a))
  a = np.array(np.matrix(szx)*np.matrix(a))
  
  print(a)

  arr = np.array([a[0],a[1],a[2]])
  tp_arr = arr.transpose()
  print(tp_arr)

  return tp_arr

In [6]:
def _3DShar(data):
  size = data.shape[1]
  reminder = size%3
  #print(size,reminder)

  #first triplate
  triplate = data[:,:3]
  print(triplate)
  merged_array = np.array(sharing(triplate))
  for i in range(3,size-reminder,3):
    triplate = data[:,i:3+i]
    Rotated = np.array(sharing(triplate))
    # Merge the arrays along the columns
    merged_array = np.concatenate((merged_array, Rotated), axis=1)

  #Rotate if any colums are left
  if reminder!=0:
    triplate = data[:,-3:]
    Rotated = np.array(sharing(triplate))
    merged_array = np.concatenate((merged_array, Rotated[:,-1*(reminder):]), axis=1)
    #print(merged_array.shape)
  return merged_array

In [7]:
df = pd.read_csv('data.csv')
df.head()
label = df['Class']
df = df.drop(columns=['Class'])
A = df.to_numpy()
print(A.shape)
newArr = _3DShar(convert(A.copy()))
print(newArr.shape)

df = pd.DataFrame(newArr)
df['Class'] = np.array(list(label))
df.to_csv("newData.csv",index=False)

(267, 44)
[[772. 868. 964. ... 772. 784. 760.]
 [784. 856. 736. ... 736. 748. 616.]
 [844. 820. 760. ... 844. 832. 796.]
 ...
 [856. 664. 736. ... 928. 640. 784.]
 [676. 652. 484. ... 772. 664. 676.]
 [784. 592. 472. ... 784. 496. 676.]]
[[772. 784. 844.]
 [868. 856. 820.]
 [964. 736. 760.]
 [832. 760. 748.]
 [712. 688. 796.]
 [784. 724. 772.]
 [928. 880. 892.]
 [784. 724. 712.]
 [892. 700. 820.]
 [796. 784. 844.]
 [748. 796. 808.]
 [748. 724. 844.]
 [820. 844. 748.]
 [736. 868. 592.]
 [712. 616. 748.]
 [652. 484. 712.]
 [772. 748. 700.]
 [712. 616. 844.]
 [772. 676. 616.]
 [748. 640. 772.]
 [820. 640. 868.]
 [844. 676. 880.]
 [892. 796. 892.]
 [760. 748. 832.]
 [796. 928. 772.]
 [856. 772. 796.]
 [760. 808. 904.]
 [916. 664. 844.]
 [700. 760. 736.]
 [724. 796. 808.]
 [844. 772. 856.]
 [760. 784. 772.]
 [628. 616. 820.]
 [808. 784. 784.]
 [820. 820. 892.]
 [652. 496. 856.]
 [832. 820. 808.]
 [688. 664. 856.]
 [364. 220. 424.]
 [664. 808. 712.]
 [664. 448. 652.]
 [892. 892. 808.]
 [748.