In [10]:
import pandas as pd
import numpy as np

In [11]:
# (2*(x-3)**2 + 4)
# (cos(2*x))


def f(x):
    return f"{(3*x + 4):.2f}"

def fdash(x):
    return 4*(x-3)

In [12]:
def convert(arr):
    arr = arr.T
    for j in range(len(arr)):
        x = arr[j]
        temp = []
        for i in x:
            temp.append(fdash(i))
        xdash = np.array(temp)
        temp = []
        for i in xdash:
            temp.append(f(i))
        arr[j] = np.array(temp)
    print(arr)
    arr = arr.T
    return arr

In [13]:
df = pd.read_csv('data.csv')
df.head()
label = df['Class']
df = df.drop(columns=['Class'])
A = df.to_numpy()
print(A.shape)
newArr = convert(A.copy())
print(newArr.shape)

df = pd.DataFrame(newArr)
df['Class'] = np.array(list(label))
df.to_csv("newData.csv",index=False)

(267, 44)
[[772. 868. 964. ... 772. 784. 760.]
 [784. 856. 736. ... 736. 748. 616.]
 [844. 820. 760. ... 844. 832. 796.]
 ...
 [856. 664. 736. ... 928. 640. 784.]
 [676. 652. 484. ... 772. 664. 676.]
 [784. 592. 472. ... 784. 496. 676.]]
(267, 44)


In [14]:
#y=a(x-h)^2 + k; y = 2(x-3)^2 + 4
#dy/dx = 2a(x-h) = x'
#y' = a(x'-h)^2 + k
print(list(label))

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
